#!/bin/bash

apt-get update
apt install docker.io -y
systemctl enable docker 
systemctl start docker
curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
apt-get update -y
apt install -y kubeadm kubelet kubectl
