#!/bin/bash

apt-get update
apt install docker.io -y
systemctl enable docker 
systemctl start docker
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key-gpg
echo "deb [signed-by-/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
apt-get update -y
apt install -y kubeadm-1.20.0-00 kubectl-1.20.0-00 kubelet-1.20.0-00 
